### PR TITLE
I am back at it again

### PR DESCRIPTION
**Pull request by greysilly7**
Converted to typescript :), should be fully working. I tested it with TS and JS works perfectly!

### CODE REVIEW

**Comment by greysilly7** [comment]
NOOOO

**Comment by greysilly7** [comment]
YOU I REALISED A MISTAKE

**Comment by greysilly7** [comment]
TIME FOR ANOTHER PR >:(

**Comment by haiderlikesrust** [comment]
Why?

**Comment by greysilly7** [comment]
shhh you shall see

**Pull request merged**
